sgi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'wenner.views.home_page', name='home'),
    url(r'^wenner/$', 'wenner.views.home_page', name='home'),

    url(r'^wenner/crea_estudio$', 'wenner.views.crea_estudio', name='crea_estudio'),
    url(r'^wenner/(\d+)/introduce_estudio$', 'wenner.views.introduce_estudio', name='introduce_estudio'),
    url(r'^wenner/(\d+)/modifica_estudio$', 'wenner.views.modifica_estudio', name='modifica_estudio'),
    url(r'^wenner/(\d+)/ver_estudio$', 'wenner.views.ver_estudio', name='ver_estudio'),

    url(r'^wenner/(\d+)/modifica_modelo$', 'wenner.views.modifica_modelo', name='modifica_modelo'),
    url(r'^wenner/(\d+)/introduce_modelo$', 'wenner.views.introduce_modelo', name='introduce_modelo'),
    url(r'^wenner/(\d+)/ver_modelo$', 'wenner.views.ver_modelo', name='ver_modelo'),

    url(r'^wenner/graficos/(.+).png$', 'wenner.views.grafico_rho_funcion_a', name='grafico_rho_funcion_a'),
    url(r'^wenner/(\d+)/reporte_pdf$', 'wenner.views.reporte_pdf', name='crea_reporte_pdf'),
]

wenner/models.py
from django.db import models
from datetime import date

class Estudio(models.Model):
    fecha = models.TextField(default='')
    nombre = models.TextField(default='')
    ubicacion = models.TextField(default='')
    humedad = models.TextField(default='')
    numero_mediciones = models.IntegerField(default=-1)
    cantidad_estratos = models.IntegerField(default=-1)
    grafico_r_funcion_a = models.ImageField(upload_to='wenner/graficos', default=None)
    grafico_modelo = models.ImageField(upload_to='wenner/graficos', default=None)

class Medicion(models.Model):
    distancia = models.FloatField(default=0)
    resistividad = models.FloatField(default=0)
    estudio = models.ForeignKey(Estudio, default=None)

class Estrato(models.Model):
    espesor = models.FloatField(default=-1)
    resistividad = models.FloatField(default=-1)
    estudio = models.ForeignKey(Estudio, default=None)

wenner/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.files.base import ContentFile
from django.core.files.base import File
from wenner.models import Estudio, Medicion, Estrato

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

import datetime
import reportlab

from io import BytesIO
from wenner.util import crea_modelo_estratos

def home_page(request):
    return render(request, 'home.html', {
        "range": range(30)
    })

def crea_estudio(request):
    num_mediciones = int(request.POST.get('num_mediciones', 0))
    fecha_texto = request.POST.get('fecha_texto', '')
    nombre_texto = request.POST.get('nombre_texto', '')
    ubicacion_texto = request.POST.get('ubicacion_texto', '')
    humedad_texto = request.POST.get('humedad_texto', '')

    estudio = Estudio.objects.create(
        fecha=fecha_texto,
        nombre=nombre_texto,
        ubicacion=ubicacion_texto,
        humedad=humedad_texto,
        numero_mediciones=num_mediciones,
    )
    return redirect('/wenner/%d/introduce_estudio' % (estudio.id,))

def introduce_estudio(request, estudio_id):
    estudio = Estudio.objects.get(id = estudio_id)
    request.session["desde"] = "introduce_estudio"

    return render(request, 'introduce_estudio.html', {
        'range': range(len(estudio.medicion_set.all()), estudio.numero_mediciones),
        'estudio': estudio,
    })

def modifica_estudio(request, estudio_id):
    estudio_ = Estudio.objects.get(id = estudio_id)

    fecha_texto = request.POST.get('fecha_texto', '')
    nombre_texto = request.POST.get('nombre_texto', '')
    ubicacion_texto = request.POST.get('ubicacion_texto', '')
    humedad_texto = request.POST.get('humedad_texto', '')
    numero_mediciones = int(request.POST.get('num_mediciones', 0))

    a = request.POST.getlist('a')
    rho = request.POST.getlist('rho')
    medicion_id = request.POST.getlist('medicion_id', [])

    if fecha_texto != '' and fecha_texto != estudio_.fecha:
        estudio_.fecha = fecha_texto
    if nombre_texto != '' and nombre_texto != estudio_.nombre:
        estudio_.nombre = nombre_texto
    if ubicacion_texto != '' and ubicacion_texto != estudio_.ubicacion:
        estudio_.ubicacion = ubicacion_texto
    if humedad_texto != '' and humedad_texto != estudio_.humedad:
        estudio_.humedad = humedad_texto

    if medicion_id == []:
        for x, y in zip(a, rho):
            if not estudio_.medicion_set.all().filter(distancia=x, resistividad=y).exists():
                medicion = Medicion.objects.create(distancia=x, resistividad=y, estudio=estudio_)

                fig = Figure()
                ax=fig.add_subplot(111)
                ax.plot([x.distancia for x in estudio_.medicion_set.all()], [x.resistividad for x in estudio_.medicion_set.all()])
                canvas=FigureCanvas(fig)

                f = BytesIO()
                fig.savefig(f)
                content_file = ContentFile(f.getvalue())
                estudio_.grafico_r_funcion_a.save('grfa%s.png' % (estudio_.id), content_file)
    else:
        while len(a) > len(medicion_id):
            medicion_id.append(None)
        for x, y, z in zip(a, rho, medicion_id):
            if z != None:
                medicion = Medicion.objects.get(id=z)
                medicion.distancia = x
                medicion.resistividad = y
                medicion.save()
            else:
                Medicion.objects.create(distancia=x, resistividad=y, estudio=estudio_)

            fig = Figure()
            ax=fig.add_subplot(111)
            ax.plot([x.distancia for x in estudio_.medicion_set.all()], [x.resistividad for x in estudio_.medicion_set.all()])
            canvas=FigureCanvas(fig)

            f = BytesIO()
            fig.savefig(f)
            content_file = ContentFile(f.getvalue())
            estudio_.grafico_r_funcion_a.save('grfa%s.png' % (estudio_.id), content_file)

    if numero_mediciones != 0 and numero_mediciones != estudio_.numero_mediciones:
        if estudio_.numero_mediciones > numero_mediciones:
            for i in range(estudio_.numero_mediciones-numero_mediciones):
                estudio_.medicion_set.all().last().delete()
                if request.session["desde"] == "ver_estudio":
                    fig = Figure()
                    ax=fig.add_subplot(111)
                    ax.plot([x.distancia for x in estudio_.medicion_set.all()], [x.resistividad for x in estudio_.medicion_set.all()])
                    canvas=FigureCanvas(fig)

                    f = BytesIO()
                    fig.savefig(f)
                    content_file = ContentFile(f.getvalue())
                    estudio_.grafico_r_funcion_a.save('grfa%s.png' % (estudio_.id), content_file)
        estudio_.numero_mediciones = numero_mediciones
        estudio_.save()
        if request.session["desde"] == "introduce_estudio":
            return redirect('/wenner/%d/introduce_estudio' % (estudio_.id,))
    else:
        estudio_.save()
        if request.session["desde"] == "introduce_estudio":
            return redirect('/wenner/%d/ver_estudio#grafico_r_funcion_a' % (estudio_.id,))
    estudio_.save()
    return redirect('/wenner/%d/ver_estudio#grafico_r_funcion_a' % (estudio_.id,))

def ver_estudio(request, estudio_id):
    request.session["desde"] = "ver_estudio"
    estudio = Estudio.objects.get(id = estudio_id)

    return render(request, 'ver_estudio.html', {
        'estudio': estudio,
        'range': range(len(estudio.medicion_set.all()), estudio.numero_mediciones),
    })

def introduce_modelo(request, estudio_id):
    estudio = Estudio.objects.get(id = estudio_id)
    if request.session["desde"] == "ver_estudio":
        estudio.cantidad_estratos = int(request.POST.get('cantidad_estratos', 0))
        estudio.save()

    request.session["desde"] = "introduce_modelo"
    return render(request, 'introduce_modelo.html', {
        'estudio': estudio,
        'range': range(len(estudio.estrato_set.all()), estudio.cantidad_estratos),
        'lim': len(estudio.estrato_set.all())-1
    })

def modifica_modelo(request, estudio_id):
    from wenner.gradiente import gradiente
    estudio_ = Estudio.objects.get(id = estudio_id)
    espesor = request.POST.getlist('espesor') + [-1]
    rho_m = request.POST.getlist('rho_m')
    estrato_id = request.POST.getlist('estrato_id', [])
    cantidad_estratos = int(request.POST.get('cantidad_estratos', 0))

    print(estudio_.estrato_set.all())
    if request.session["desde"] == "introduce_modelo":
        if estrato_id == []:
            print("vacio")
            print(estudio_.cantidad_estratos)
            # crea objetos
            for x, y in zip(rho_m, espesor):
                Estrato.objects.create(resistividad = x, espesor = y, estudio = estudio_)
        else:
            # modificamos objetos existentes
            for x, y, id_ in zip(rho_m, espesor, estrato_id):
                estrato = Estrato.object.get(id = id_)
                estrato.resistividad = x
                estrato.espesor = y
                estrato.save()

        print(estudio_.cantidad_estratos)
        print(type(estudio_.cantidad_estratos))
        print(cantidad_estratos)
        print(type(cantidad_estratos))
        if cantidad_estratos != estudio_.cantidad_estratos:
            if cantidad_estratos < estudio_.cantidad_estratos:
                for estrato in range(estudio_.cantidad_estratos - cantidad_estratos):
                # borramos objetos sobrantes
                    estrato = estudio_.estrato_set.all().last()
                    estrato.delete()
            if cantidad_estratos > estudio_.cantidad_estratos:
                # agregamos objetos
                pass
            estudio_.cantidad_estratos = cantidad_estratos
            estudio_.save()
            return redirect('/wenner/%d/introduce_modelo' % (estudio_.id,))
        else:
            crea_modelo_estratos(request, estudio_)
            return redirect('/wenner/%d/ver_modelo' % (estudio_.id,))
                
    else:
        pass
        # bla bla
                

def modifica_modelo_original(request, estudio_id):
    from wenner.gradiente import gradiente
    estudio_ = Estudio.objects.get(id = estudio_id)

    espesor = request.POST.getlist('espesor') + [-1]
    rho_m = request.POST.getlist('rho_m')
    estrato_id = request.POST.getlist('estrato_id', [])
    cantidad_estratos = int(request.POST.get('cantidad_estratos', 0))

    if estrato_id == []:
        for x, y in zip(espesor, rho_m):
            if not estudio_.estrato_set.all().filter(espesor=x, resistividad=y).exists():
                espesor = Estrato.objects.create(espesor=x, resistividad=y, estudio=estudio_)
    else:
        while len(rho_m) > len(estrato_id):
            estrato_id.append(None)
        for x, y, z in zip(espesor, rho_m, estrato_id):
            if z != None:
                estrato = Estrato.objects.get(id=z)
                estrato.espesor = x
                estrato.resistividad = y
                estrato.save()
            else:
                Estrato.objects.create(espesor=x, resistividad=y, estudio=estudio_)

    p = [0] + [x.espesor for x in estudio_.estrato_set.all()][:-1] + [x.resistividad for x in estudio_.estrato_set.all()]
    p += [0 for x in range(21-len(p))]
    xw = [0] + [x.distancia for x in estudio_.medicion_set.all()]
    rf = [0] + [x.resistividad for x in estudio_.medicion_set.all()]
    il = estudio_.cantidad_estratos
    jz = estudio_.numero_mediciones

    (ik, it, p, q, jm, ic, jz, xw, rf, rmod, bm) = gradiente(il, p, jz, xw, rf)
    p = p[1:]
    p1 = []
    p2 = []
    for i in range(ik):
        p1.append(p[i+ik])
        p2.append(p[i])
    p0 = zip(p1, p2)
    p3 = p[it-1]
    rf = rf[1:]
    rmod = rmod[1:]
    xw = xw[1:]

    rf_rmod = []
    for i in range(jz):
        rf_rmod.append(1-rmod[i]/rf[i])

    fig = Figure()
    ax=fig.add_subplot(111)

wenner/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Interpretación de las Mediciones de Resistividad Aparente</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/static/bootstrap/css/wenner.css" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="text-center">
                    <h1>{% block cabecera %}{% endblock %}</h1>
                    <div id="texto_bienvenida">
                        {% block texto_bienvenida %}{% endblock %}
                    </div>
                    {% block cuerpo %}{% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

wenner/templates/home.html
{% extends 'base.html' %}

{% block cabecera %}Cree un modelo estratificado{% endblock %}

{% block texto_bienvenida %}
            <p>
                Use esta aplicación para, después de haber realizado mediciones usando el método de Wenner, graficar una curva que muestre las resistividades aparentes en función de las distancias de cada medición, y también para obtener los parámetros de resistividad y espesor de un modelo de terreno de n estratos horizontales que aproxime las mediciones hechas en campo.
            </p>
            <p>
                Introduzca, opcionalmente, la fecha cuando fueron hechas estas medidas, su nombre o el su organización, la ubicación donde se realizaron las medidas, la humedad del terreno al haber tomado las medidas.
            </p>
{% endblock %}

{% block cuerpo %}
        <form method="POST" action="/wenner/crea_estudio">
            <div class="form-group form-inline">
                <input class="form-control" id="id_fecha" name="fecha_texto" placeholder="Fecha" />
                <input class="form-control" id="id_nombre" name="nombre_texto" placeholder="Nombre" />
                <input class="form-control" id="id_ubicacion" name="ubicacion_texto" placeholder="Ubicación" />
                <input class="form-control" id="id_humedad" name="humedad_texto" placeholder="Humedad del terreno" />
                <input class="form-control" id="id_num_mediciones" name="num_mediciones" type="number" min="1" placeholder="Número de mediciones" required />
                <input class="form-control" type="submit" id="enviar" />
            </div>
            {% csrf_token %}
        </form>
{% endblock %}

wenner/templates/introduce_modelo.html
{% extends 'base.html' %}

{% block cuerpo %}
        <form method="POST">
            <div class="form-group form-inline">
                <input class="form-control" id="id_fecha" name="fecha_texto" placeholder="Fecha" value="{{ estudio.fecha }}" />
                <input class="form-control" id="id_nombre" name="nombre_texto"  placeholder="Nombre" value="{{ estudio.nombre }}"/>
                <input class="form-control" id="id_ubicacion" name="ubicacion_texto" placeholder="Ubicación" value="{{ estudio.ubicacion }}" />
                <input class="form-control" id="id_humedad" name="humedad_texto" placeholder="Humedad" value="{{ estudio.humedad }}" />
            </div>
            <table class="table table-stripped table-bordered table-condensed table-auto">
                <tr>
                    <th>Distancia</th>
                    <th>Resistividad</th>
                </tr>
                {% for medicion in estudio.medicion_set.all %}
                <tr>
                    <td><input class="form-control input-tabled" id="a{{ forloop.counter | add:-1 }}" name="a" type="number" step="any" placeholder="Distancia {{ forloop.counter }}" value="{{ medicion.distancia|floatformat:3 }}" required /></td>
                    <td><input class="form-control input-tabled" id="rho{{ forloop.counter | add:-1 }}" name="rho" type="number" step="any" placeholder="Resistividad {{ forloop.counter }}" value="{{ medicion.resistividad|floatformat:3 }}" required /></td>
                </tr>
                <input name="medicion_id" value="{{medicion.id}}" type="hidden" />
                {% endfor %}
            </table>
            <input class="btn btn-default" type="submit" id="enviar" />
            {% csrf_token %}
        </form>
        <img class="img-responsive center-block" id="grafico_r_funcion_a" src="/{{ estudio.grafico_r_funcion_a.url }}" alt="gráfico de la resistividad en función de la distancia">
        <div id="texto_instructivo_2">
            <p>
                Introduzca los datos de espesor y resistividad para su modelo
            </p>
        </div>
        <form method="POST" action="/wenner/{{ estudio.id }}/modifica_modelo">
            <div class="form-group form-inline">
                <input id="id_cantidad_estratos" name="cantidad_estratos" type="number" min="1" placeholder="Cantidad de estratos" value="{{ estudio.cantidad_estratos }}" required />
            </div>
            <table class="table table-stripped table-bordered table-condensed table-auto">
                <tr>
                    <th>Resistividad</th>
                    <th>Espesor</th>
                </tr>
                {% if not estudio.estrato_set.all %}
                {% for estrato in range %}
                <tr>
                    <td><input class="form-control input-tabled" id="rho_m{{ forloop.counter | add:-1 }}" name="rho_m" type="number" step="any" placeholder="Resistividad del estrato {{ forloop.counter }}" required /></td>
                {% if forloop.counter < estudio.cantidad_estratos %}
                    <td><input class="form-control input-tabled" id="espesor{{ forloop.counter | add:-1 }}" name="espesor" type="number" step="any" placeholder="Espesor del estrato {{ forloop.counter }}" required /></td>
                {% endif %}
                </tr>
                {% endfor %}

                {% else %}
                {% for estrato in estudio.estrato_set.all %}
                <tr>
                    <td><input class="form-control input-tabled" id="rho_m{{ forloop.counter | add:-1 }}" name="rho_m" type="number" step="any" placeholder="Resistividad del estrato {{ forloop.counter }}" value="{{ estrato.resistividad }}" required /></td>
                {% if forloop.counter < estudio.estrato_set.all.count %}
                    <td><input class="form-control input-tabled" id="espesor{{ forloop.counter | add:-1 }}" name="espesor" type="number" step="any" placeholder="Espesor del estrato {{ forloop.counter }}" value="{{ estrato.espesor }}" required /></td>
                </tr>
                {% endif %}
                {% endfor %}
                {% for i in range %}
                <tr>
                    <td><input class="form-control input-tabled" id="rho_m{{ i }}" name="rho_m" type="number" step="any" placeholder="Resistividad del estrato {{ i|add:1 }}" required /></td>
                    <td><input class="form-control input-tabled" id="espesor{{ i }}" name="espesor" type="number" step="any" placeholder="Espesor del estrato {{ i|add:1 }}" required /></td>
                </tr>
                {% endfor %}
                {% endif %}
            </table>
            <input type="submit" id="segundo_enviar" />
            {% csrf_token %}
        </form>
{% endblock %}

wenner/templates/template.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>My Title</title>
        <style type="text/css">
            @page {
                size: {{ pagesize }};
                margin: 1cm;
                @frame footer {
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 9cm;
                    margin-right: 9cm;
                    height: 1cm;
                }
            }
        </style>
    </head>
    <body>
        <div>
            {% for item in mylist %}
                RENDER MY CONTENT
            {% endfor %}
        </div>
        <div id="footerContent">
            {%block page_foot%}
                Page <pdf:pagenumber>
            {%endblock%}
        </div>
    </body>
</html>

wenner/templates/ver_estudio.html
{% extends 'base.html' %}

{% block cabecera %}{% endblock %}

{% block cuerpo %}
        <div id="texto_instructivo">
            <p>
                Puede modificiar los datos introducidos de ser necesario
            </p>
        </div>
        <form method="POST" action="/wenner/{{ estudio.id }}/modifica_estudio">
            <div class="form-group form-inline">
                <input class="form-control" id="id_fecha" name="fecha_texto" placeholder="Fecha" value="{{ estudio.fecha }}" />
                <input class="form-control" id="id_nombre" name="nombre_texto"  placeholder="Nombre" value="{{ estudio.nombre }}"/>
                <input class="form-control" id="id_ubicacion" name="ubicacion_texto" placeholder="Ubicación" value="{{ estudio.ubicacion }}" />
                <input class="form-control" id="id_humedad" name="humedad_texto" placeholder="Humedad" value="{{ estudio.humedad }}" />
                <input class="form-control" id="id_num_mediciones" name="num_mediciones" type="number" min="1" placeholder="Número de mediciones" value="{{ estudio.numero_mediciones }}" required />
            </div>

            <table class="table table-stripped table-bordered table-condensed table-auto">
                <tr>
                    <th>Distancia</th>
                    <th>Resistividad</th>
                </tr>
                {% for medicion in estudio.medicion_set.all %}
                    <tr>
                        <td><input class="form-control input-tabled" id="a{{ forloop.counter | add:-1 }}" name="a" type="number" step="any" placeholder="Distancia {{ forloop.counter }}" value="{{ medicion.distancia|floatformat:3 }}" required /></td>
                        <td><input class="form-control input-tabled" id="rho{{ forloop.counter | add:-1 }}" name="rho" type="number" step="any" placeholder="Resistividad {{ forloop.counter }}" value="{{ medicion.resistividad|floatformat:3 }}" required /></td>
                <input name="medicion_id" value="{{medicion.id}}" type="hidden" />
                {% endfor %}
                {% for i in range %}
                <tr>
                    <td><input class="form-control input-tabled" id="a{{ i }}" name="a" type="number" step="any" placeholder="Distancia {{ i|add:1 }}" required /></td>
                    <td><input class="form-control input-tabled" id="rho{{ i }}" name="rho" type="number" step="any" placeholder="Resistividad {{ i|add:1 }}" required /></td>
                </tr>
                {% endfor %}
            </table>
            <input type="submit" id="enviar" class="btn btn-default" />
            {% csrf_token %}
        </form>
        <img class="img-responsive center-block" id="grafico_r_funcion_a" src="/{{ estudio.grafico_r_funcion_a.url }}" alt="gráfico de la resistividad en función de la distancia">

        <h2>Puede introducir los datos para generar el modelo estratificado</h2>
        <div id="texto_instructivo_2">
            <p>
                Puede generar un modelo de n estratos horizontales que indique los parámetros de resistividad y espesor para aproximar los datos que ya introdujo.
            </p>
            <p>
                Indique el número de estratos
            </p>
        </div>
        <form method="POST" action="/wenner/{{ estudio.id }}/introduce_modelo">
            <input id="id_cantidad_estratos" name="cantidad_estratos" type="number" min="1" placeholder="Cantidad de estratos" required />
            <input type="submit" id="segundo_enviar" class="btn btn-default" />
            {% csrf_token %}
        </form>
{% endblock %}

wenner/templates/ver_modelo.html
{% extends 'base.html' %}

{% block cuerpo %}
        <form method="POST">
            <div class="form-group form-inline">
                <input class="form-control" id="id_fecha" name="fecha_texto" placeholder="Fecha" value="{{ estudio.fecha }}" />
                <input class="form-control" id="id_nombre" name="nombre_texto"  placeholder="Nombre" value="{{ estudio.nombre }}"/>
                <input class="form-control" id="id_ubicacion" name="ubicacion_texto" placeholder="Ubicación" value="{{ estudio.ubicacion }}" />
                <input class="form-control" id="id_humedad" name="humedad_texto" placeholder="Humedad" value="{{ estudio.humedad }}" />
            </div>
            <table class="table table-stripped table-bordered table-condensed table-auto">
                <tr>
                    <th>Distancia</th>
                    <th>Resistividad</th>
                </tr>
            {% for medicion in estudio.medicion_set.all %}
                <tr>
                    <td><input class="form-control input-tabled" id="a{{ forloop.counter | add:-1 }}" name="a" type="number" step="any" placeholder="Distancia {{ forloop.counter }}" value="{{ medicion.distancia|floatformat:3 }}" required /></td>
                    <td><input class="form-control input-tabled" id="rho{{ forloop.counter | add:-1 }}" name="rho" type="number" step="any" placeholder="Resistividad {{ forloop.counter }}" value="{{ medicion.resistividad|floatformat:3 }}" required /></td>
                <input name="medicion_id" value="{{medicion.id}}" type="hidden" />
                </tr>
            {% endfor %}
            </table>
            <input type="submit" class="btn btn-default" id="enviar" />
            {% csrf_token %}
        </form>
        <img class="img-responsive center-block" id="grafico_r_funcion_a" src="/{{ estudio.grafico_r_funcion_a.url }}" alt="gráfico de la resistividad en función de la distancia">

        <form method="POST" action="/wenner/{{ estudio.id }}/modifica_modelo">
            <input id="id_cantidad_estratos" name="cantidad_estratos" type="number" min="1" placeholder="Cantidad de estratos" value="{{ estudio.cantidad_estratos }}" required />
            
            <table class="table table-stripped table-bordered table-condensed table-auto">
                <tr>
                    <th>Resistividad</th>
                    <th>Espesor</th>
                </tr>
                {% for estrato in estudio.estrato_set.all %}
                <tr>
                    <td><input class="form-control input-tabled" id="rho_m{{ forloop.counter | add:-1 }}" name="rho_m" type="number" step="any" placeholder="Resistividad del estrato {{ forloop.counter }}" value="{{ estrato.resistividad|floatformat:3 }}" required /></td>
                {% if forloop.counter < estudio.cantidad_estratos %}
                    <td><input class="form-control input-tabled" id="espesor{{ forloop.counter | add:-1 }}" name="espesor" type="number" step="any" placeholder="Espesor del estrato {{ forloop.counter }}" value="{{ estrato.espesor|floatformat:3 }}" required /></td>
                {% endif %}
                </tr>
                <input name="estrato_id" value="{{ estrato.id }}" type="hidden" />
                {% endfor %}
            </table>
            <input type="submit" class="btn btn-default" id="segundo_enviar" />
            {% csrf_token %}
        </form>
        <div class="panel panel-default">
            <div class="panel-heading">Modelo</div>
            <div class="panel-body">
                <table class="table table-stripped table-bordered table-auto" id="tabla_resistividad_espesor">
                    <tr>
                        <th>Resistividad</th>
                        <th>Espesor</th>
                    </tr>
                    {% for p1, p2 in p0 %}
                    <tr>
                        <td>{{ p1|floatformat:3 }}</td>
                        <td>{{ p2|floatformat:3 }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td>{{ p3|floatformat:3 }}</td>
                        <td></td>
                    </tr>
                </table>
                <p id="error_rms">error relativo rms: {{q|floatformat:3}}</p>
                <p id="error_maximo">error relativo máximo: {{bm|floatformat:3}}, en la muestra {{jm}}</p>
                <p id="cantidad_iteraciones">cantidad de iteraciones: {{ic}}</p>
                <table class="table table-stripped table-bordered table-auto" id="tabla_a_rc_rm_er">
                    <tr>
                        <th>Distancia</th>
                        <th>Resistividad Campo</th>
                        <th>Resistividad Modelo</th>
                        <th>Error Relativo</th>
                    </tr>
                    {% for xw, rf, rmod, rf_rmod in r %}
                    <tr>
                        <td>{{ xw|floatformat:3 }}</td>
                        <td>{{ rf|floatformat:3 }}</td>
                        <td>{{ rmod|floatformat:3 }}</td>
                        <td>{{ rf_rmod|floatformat:3 }}</td>
                    </tr>
                    {% endfor %}
                </table>
                <img class="img-responsive center-block" id="grafico_modelo" src="/{{ estudio.grafico_modelo.url }}" alt="gráfico de la resistividad en función de la distancia y la resistividad proporcionada por el modelo en función de la distancia">
            </div>
        </div>
{% endblock %}